
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-835bdefc
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
resources:
- ../../base
images:
- name: trial-backend
  newName: /trial-backend
  newTag: 1447e68bdcd939d9205a283e21a40e9a6e06f0e3
