
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-835bdefc
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
resources:
- ../../base
images:
- name: trial-backend
  newName: 670927678896.dkr.ecr.us-east-1.amazonaws.com/trial-backend
  newTag: dc51116deee75ec535208cf2875504703dcf6cd8
