
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-835bdefc
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
resources:
- ../../base
images:
- name: trial-backend
  newName: '670927678896.dkr.ecr.us-east-1.amazonaws.com/trial-backend:'
  newTag: a2351463b03cc8dfd91f36868cd6f3af022f2d9c
