# This is a basic workflow to help you get started with Actions

name: Deploy to ECR

# Controls when the workflow will run
on:
  workflow_dispatch:
  # Ignore changes on the infra/ folder to avoid re-building the docker image on infrastructure configuration changes.
  push:
    branches: 
      - main 
    paths-ignore:
      - 'infra/app-services/**'
      - 'infra/helm/**'
      - 'infra/**'
      - '.github/workflows/**'
      - '.github/**'
jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        AWS_ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        AWS_ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t "$AWS_ECR_REGISTRY/$AWS_ECR_REPOSITORY:$IMAGE_TAG" .
        docker push "$AWS_ECR_REGISTRY/$AWS_ECR_REPOSITORY:$IMAGE_TAG"
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "4.5.7"

    - name: Update Kubernetes resources
      env:
        AWS_ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        AWS_ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
       cd infra/manifests/overlays/staging
       kustomize edit set image trial-backend="670927678896.dkr.ecr.us-east-1.amazonaws.com/trial-backend::$IMAGE_TAG"
       cat kustomization.yaml
        
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Bump docker tag"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}